declare namespace BreezeRuntime {
  export interface DeploymentInfo {
    projectId: string;
    environmentId: string;
    functionId: string;
  }

  export interface Plugin {
    id: string;
    endpoint: string;
  }

  /**
   * An JWT token generated by Breeze to authorize plugin  or workflow requests.
   */
  export type Token = string;

  export interface TokenOptions {
    /**
     * The instance name of plugin.
     */
    plugin?: string;
  }

  export function getDeploymentInfo(): DeploymentInfo;

  export function getPlugin(plugin: string): Plugin | null;

  export function generateToken(opts?: TokenOptions): Token;

  export function pluginFetch(plugin: string): Promise<Response>;

  export function pluginFetch(plugin: string, path: string): Promise<Response>;

  export function pluginFetch(
    plugin: string,
    opts: RequestInit,
  ): Promise<Response>;

  export function pluginFetch(
    plugin: string,
    path: string,
    opts: RequestInit,
  ): Promise<Response>;
}
